# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c941149d7223a88914e01c83635b80b840cdc9e25f81e8af5afc56c3e10e82db49a98fada6b846e366815ddc1a70aa71c7e5ff9704019a0ef79ccb7ff88942d

test:
  secret_key_base: 6837ab6a4b9bbe994a4c7e98f0fa079f5db3478e80523aef7a5b185b7208b034346ec652d59f4cee8f7f8a89d001bbc0dc4592ec51d49c9a680ac7b1f8524623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
